### PR TITLE
Warning on invalid gear addition

### LINKED ISSUE #196: Add invalid input warning on the  'Add Item By ID' input
We should give the user a feedback when the 'Add Item By Id' was unsuccessful.

### PR DESCRIPTION
**Pull request by VanSHOE**
Fixes #196 
Added alert on invalid addition
Please let me know if this is what was required

### CODE REVIEW

**Comment by orichalque** [comment]
Thanks for your contribution, we really appreciate ! 
Would that be possible for you to replace the `if(found == false) {` by a `if(!found) {` ?
Furthermore, we do not use the built-in javascript `alert()`, instead we provided our own alert dialog, such as : 
`this.showRedAlert("your_warning")` 
You can find some examples in the abilities.js file. 
Would that be possible for you to replace the `alert()` with ours ?

Thanks again for your contribution :)

**Comment by VanSHOE** [comment]
Sure, will do

**Comment by VanSHOE** [comment]
Does this seem okay?

**Comment by orichalque** [comment]
image
Great :) 
We have a lot on changes going on atm, but it should come to master soon ! Thanks a lot.

**Pull request merged**
