### PR TITLE
Darkmode

### PR DESCRIPTION
**Pull request by orichalque**
#52

### CODE REVIEW

**Comment by orichalque** [comment]
There's a bug in the Add Item by ID input field, it refreshes the page when pressing enter instead of adding the item. 
I'll fix this asap

**Comment by RaphaelPage0110** [comment]
The 'Accept cookies' message police should be white 
image

**Comment by RaphaelPage0110** [comment]
The rest looks perfect :D 
Awesome work, we will soon be able to close one of our oldest issue!!!

**Review by RaphaelPage0110 — CHANGES_REQUESTED** [review]
See above comment

**Comment by orichalque** [comment]
> The 'Accept cookies' message police should be white image

good call :)

**Pull request merged**
